// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDquuQdr2_y64ryxjW8CFCn8ZtE1ybr4Xg',
    appId: '1:129324335685:web:11a3a80f4c94181b1ad92c',
    messagingSenderId: '129324335685',
    projectId: 'cardioguard-1a6fa',
    authDomain: 'cardioguard-1a6fa.firebaseapp.com',
    storageBucket: 'cardioguard-1a6fa.firebasestorage.app',
    measurementId: 'G-N67RHPH3MF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG1kUicJNlza4_Lp0I6A5KdFxWRfpE4Fo',
    appId: '1:129324335685:android:19c5274e08f04b291ad92c',
    messagingSenderId: '129324335685',
    projectId: 'cardioguard-1a6fa',
    storageBucket: 'cardioguard-1a6fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCinxbeWrjx7ZV5NaH8_i0krW_w6DSI4fE',
    appId: '1:129324335685:ios:302452960773dcc31ad92c',
    messagingSenderId: '129324335685',
    projectId: 'cardioguard-1a6fa',
    storageBucket: 'cardioguard-1a6fa.firebasestorage.app',
    iosBundleId: 'com.example.cardiogaurd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCinxbeWrjx7ZV5NaH8_i0krW_w6DSI4fE',
    appId: '1:129324335685:ios:302452960773dcc31ad92c',
    messagingSenderId: '129324335685',
    projectId: 'cardioguard-1a6fa',
    storageBucket: 'cardioguard-1a6fa.firebasestorage.app',
    iosBundleId: 'com.example.cardiogaurd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDquuQdr2_y64ryxjW8CFCn8ZtE1ybr4Xg',
    appId: '1:129324335685:web:f8a3306c45cbe5f51ad92c',
    messagingSenderId: '129324335685',
    projectId: 'cardioguard-1a6fa',
    authDomain: 'cardioguard-1a6fa.firebaseapp.com',
    storageBucket: 'cardioguard-1a6fa.firebasestorage.app',
    measurementId: 'G-9PBZ5QMNDQ',
  );
}